In [29]:
import numpy as np

x = np.array([[1, 2], [4, 5]]) 
y = np.array([[7], [9]]) 
b = np.array([[7, 8], [9, 10]]) 


x3 = np.array([[1, 2, 6], [4, 5, 9], [4, 5, 1]]) 
b3 = np.array([[7, 8, 7], [9, 10, 7], [4, 5, 0]]) 
y3 = np.array([[7], [9], [4]]) 


In [30]:
print(x,"\n")
print(y,"\n")
print(x3,"\n")
print(y3,"\n")
print(b,"\n")
print(b3,"\n")


[[1 2]
 [4 5]] 

[[7]
 [9]] 

[[1 2 6]
 [4 5 9]
 [4 5 1]] 

[[7]
 [9]
 [4]] 

[[ 7  8]
 [ 9 10]] 

[[ 7  8  7]
 [ 9 10  7]
 [ 4  5  0]] 



## Element wise operations

In [21]:
print(np.add(x,y),"\n")
print(np.subtract(x,y),"\n")
print(np.divide(x,y),"\n")
print(np.sqrt(x),"\n")

[[ 8 10]
 [13 15]] 

[[-6 -6]
 [-5 -5]] 

[[0.14285714 0.25      ]
 [0.44444444 0.5       ]] 

[[1.         1.41421356]
 [2.         2.23606798]] 



## Matrix operations

In [27]:
print("Multiplication: \n",np.dot(x,y),"\n")
print("Transpose: \n",x.T,"\n")
print("Deteminant: \n",np.linalg.det(x),"\n")
print("Inverse: \n",np.linalg.inv(x),"\n")
print("Proof: \n",np.dot(x,np.linalg.inv(x)),"\n")



Multiplication: 
 [[25 28]
 [73 82]] 

Transpose: 
 [[1 4]
 [2 5]] 

Deteminant: 
 -2.9999999999999996 

Inverse: 
 [[-1.66666667  0.66666667]
 [ 1.33333333 -0.33333333]] 

Proof: 
 [[1. 0.]
 [0. 1.]] 



## Solving ecuations

$$\begin{bmatrix}1 & 1 & 1 \\0 & 2 & 5 \\2 & 5 & -1\end{bmatrix} \begin{bmatrix}x \\y \\z \end{bmatrix} = \begin{bmatrix}6 \\-4 \\27 \end{bmatrix}$$

$A*X = B$

Or

$X = A-1B$

In [35]:
print("Solving 3x3 problems: \n",np.linalg.solve(x3,y3),"\n")
xinv = np.linalg.inv(x3)
print("Analitically solving 3x3 problems: \n",np.dot(xinv,y3),"\n")



Solving 3x3 problems: 
 [[-3.16666667]
 [ 3.20833333]
 [ 0.625     ]] 

Analitically solving 3x3 problems: 
 [[-3.16666667]
 [ 3.20833333]
 [ 0.625     ]] 



In [33]:
np.linalg.solve(x,y)

array([[-5.66666667],
       [ 6.33333333]])