# Biblioteca Numpy

### Arreglos en NumPy

In [1]:
import numpy as np

data = np.random.randn(2, 3)

In [1]:
for i = 0; i <= 15; i++{
    print(i)
}

SyntaxError: invalid syntax (<ipython-input-1-c65393361594>, line 1)

In [ ]:

TEST_DATA = [
    ('Lorem ipsum',
     'Lorem ipsum'),
    ('Lorem ipsum a@a.com dolor sit amet',
     'Lorem ipsum ...@a.com dolor sit amet'),
    ('Lorem ipsum --@--.--',
     'Lorem ipsum --@--.--'),
    ('Lorem some@data ipsum',
     'Lorem some@data ipsum'),
    ('Lorem B@bb12.com ipsum',
     'Lorem ...@bb12.com ipsum'),
    ('Lorem abc-abc@abc.edu.co.uk am',
     'Lorem ...@abc.edu.co.uk am'),
    ('Lorem cBa-abC@abc.edu.co.uk. dolor',
     'Lorem ...@abc.edu.co.uk. dolor'),
    ('Lorem dsad BB12@BB-12.COM. dolor',
     'Lorem dsad ...@BB-12.COM. dolor'),
    ('Lorem XXd -abc_ABC@abc.edu. dolor',

In [72]:
import re
text = 'Lorem XXd -abc_ABC@abc.edu. dolor'
replacement = 'xxx'
emailsToReplace = [(replacement+email[email.find('@'):],email) for email in re.findall('[a-zA-Z0-9._\-]+@[a-zA-Z]+[a-zA-Z._\-\+]*', text)]
emailsToReplace
for emailToReplace,email in emailsToReplace:
#     print(ema)
    text = text.replace(email,emailToReplace)
    
text

   

'Lorem XXd xxx@abc.edu. dolor'

In [84]:
import re        
text = '<a href="skype:LOREN?chat"/>'
replacement = 'x'
skypesToReplace = [("skype:" + replacement+skype[skype.find(':'):skype.find('?')],skype) for skype in re.findall('skype:[a-zA-Z0-9]+\?', text)]
skypesToReplace
skype[skype.find(':')+1:skype.find('?')]
text.replace(skype[skype.find(':')+1:skype.find('?')],"#")
# for skypeToReplace,skype in skypesToReplace:
# #     print(ema)
#     text = text.replace(skype[skype.find(':')+1:skype.find('?')],"#")

# text

'<a href="skype:#?chat"/>'

In [3]:
s="sing"
s[1] = 'o'

TypeError: 'str' object does not support item assignment

In [35]:
data

[[1, 2, 3], [4, 5, 6]]

In [33]:
np.linspace(1,4,16)

array([1. , 1.2, 1.4, 1.6, 1.8, 2. , 2.2, 2.4, 2.6, 2.8, 3. , 3.2, 3.4,
       3.6, 3.8, 4. ])

In [36]:
print(data)
data * 10,  data + data

[[1, 2, 3], [4, 5, 6]]


([[1, 2, 3],
  [4, 5, 6],
  [1, 2, 3],
  [4, 5, 6],
  [1, 2, 3],
  [4, 5, 6],
  [1, 2, 3],
  [4, 5, 6],
  [1, 2, 3],
  [4, 5, 6],
  [1, 2, 3],
  [4, 5, 6],
  [1, 2, 3],
  [4, 5, 6],
  [1, 2, 3],
  [4, 5, 6],
  [1, 2, 3],
  [4, 5, 6],
  [1, 2, 3],
  [4, 5, 6]],
 [[1, 2, 3], [4, 5, 6], [1, 2, 3], [4, 5, 6]])

Estos arreglos de numpy podemos crearlos a partir de arreglos de python, por ejemplo:


In [5]:
data = [[1,2,3], [4,5,6]]
arr = np.array(data)



Y ahora podemos utilizar operaciones como `shape` o `dim`

In [6]:
print(arr.shape)
print(arr.ndim)

(2, 3)
2


In [7]:
arr

array([[1, 2, 3],
       [4, 5, 6]])

### Indexando arreglos

In [8]:
arr = np.arange(8)

In [9]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7])

In [10]:
arr[5] # vemos el elemento en la posición 5 (contando desde el 0)

5

In [11]:
arr[2:5] # desde la pos 2 a la 4.

array([2, 3, 4])

In [12]:
arr[:] = 58 # Si asignamos un valor esto será _broadcasteado_ a todo el rango 

In [13]:
arr

array([58, 58, 58, 58, 58, 58, 58, 58])

### Slicing

In [14]:
arr2d = np.array([[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9]])



In [15]:
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [16]:
arr2d[:1]

array([[1, 2, 3]])

In [17]:
arr2d[:2, :]

array([[1, 2, 3],
       [4, 5, 6]])

In [18]:
arr2d[1, :2]

array([4, 5])

In [19]:
arr2d[:2, 1:] = 0
arr2d

array([[1, 0, 0],
       [4, 0, 0],
       [7, 8, 9]])

### Filtros booleanos

In [20]:
arr2d

array([[1, 0, 0],
       [4, 0, 0],
       [7, 8, 9]])

In [21]:
arr2d < 2

array([[ True,  True,  True],
       [False,  True,  True],
       [False, False, False]])

In [22]:
arr2d[arr2d < 2]

array([1, 0, 0, 0, 0])

In [23]:
arr2d > 0

array([[ True, False, False],
       [ True, False, False],
       [ True,  True,  True]])

In [24]:
arr2d[arr2d > 0]

array([1, 4, 7, 8, 9])

### Funciones universales

In [25]:
arr = np.arange(10)
arr


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [26]:
np.sqrt(arr)


array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [27]:
np.abs([-2, 1, -3])

array([2, 1, 3])

In [28]:
np.square(arr)

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)

In [29]:
np.add(arr, arr)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

### Funciones de agregación

In [30]:
arr = np.random.randn(5, 4)
arr

array([[ 1.41826368,  0.76762012,  0.4595177 , -1.73685063],
       [-0.84593361,  0.1393398 ,  1.19281645,  0.44563018],
       [-0.31104827,  0.72874555,  0.26897765,  1.39574209],
       [-0.56162539, -0.0281334 ,  1.43873456, -0.1433645 ],
       [-0.65649667,  0.5372531 ,  0.83660609, -1.7599987 ]])

In [31]:
arr.mean() # o np.mean(arr)

0.1792897899189235

In [32]:
arr.sum()

3.58579579837847